ACEsuit/mace

- mace/calculators/__init__.py
- mace/calculators/mace.py
- mace/data/atomic_data.py
- mace/data/utils.py
- mace/modules/__init__.py
- mace/modules/blocks.py
- mace/modules/loss.py
- mace/modules/models.py
- mace/modules/utils.py
- mace/tools/arg_parser.py
- mace/tools/train.py
- scripts/run_train.py
- scripts/utils.py
- tests/test_models.py
This pull request implements a MACE model that can predict l=1 equivariant outputs, molecular dipoles as the most trivial example.
> Dipole MACE model

- README.md
- mace/data/__init__.py
- mace/data/hdf5_dataset.py
- mace/data/utils.py
- mace/tools/__init__.py
- mace/tools/arg_parser.py
- mace/tools/scripts_utils.py
- scripts/preprocess_data.py
- scripts/run_train.py
This pull request implements on the fly dataloading to deal with larger than memory datasets.
> on the fly data loading

- docs/guide/lammps.rst
I've quickly converted our internal instructions to `.rst`, and I'll plan to update them here now instead of in Slack.
Perhaps we should wait to merge until things settle a bit more? What do you think?
> LAMMPS docs

- docs/guide/lammps.rst
Hi @ilyes319, does this seem sensible to you? I assume it does nothing if the model is already cpu?
> in lammps docs, ensure model is cpu model.

- mace/tools/scripts_utils.py
- mace/tools/train.py
- scripts/run_train.py
MIT License
Copyright (c) [year] [fullname]
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND …
> not break if exponential LR

- mace/calculators/lammps_mace.py
Suggestion from @davkovacs and @ilyes319.
> hopefully limit unnecessary memory use.

- mace/calculators/lammps_mace.py
- scripts/create_lammps_model.py
Hi @ilyes319, would you mind looking over these changes?
> Lammps wrapper

- docs/examples/foundation_models.rst
- docs/examples/training_examples.rst
- docs/guide/training.rst
Related PR to different branch #188.
> Add "Pretrained Universal Checkpoints" section to `docs/guide/training.rst`

- mace/calculators/mace.py
> add deprecated model_path arg to asse calculator

- mace/calculators/foundations_models.py
- mace/calculators/mace.py
- mace/cli/active_learning_md.py
- mace/cli/eval_configs.py
- mace/cli/run_train.py
- mace/tools/torch_geometric/README.md
- mace/tools/torch_geometric/data.py
- Include medium and large materials project mace models
- Better support of the float type of models in the ASE calculator
- Minor reformatting
> Add better interface to materials project models

- mace/calculators/foundations_models.py
- tests/test_calculator.py
a1c2804 fix typo `models_paths`->`model_paths`
2a88218 add `test_mace_mp()`
> Test `mace_mp()`

- mace/calculators/foundations_models.py
- tests/test_calculator.py
> Improve `mace_mp` test

- mace/cli/run_train.py
- mace/tools/arg_parser.py
- mace/tools/torch_tools.py
This PR adds the Intel XPU device abstraction to run MACE on Ponte Vecchio hardware
> Add Intel XPU device 

- mace/data/neighborhood.py
> Fix shifts to compensate for swapping sender/receiver

- mace/calculators/mace.py
@ilyes319 @jharrymoore this is a little hacky but should enable use of the ASE calculator in Intel.
> Enable ASE calculator on intel.

- mace/calculators/mace.py
- mace/modules/models.py
- mace/modules/utils.py
- mace/tools/torch_tools.py
- tests/test_calculator.py
- tests/test_hessian.py
- tests/test_run_train.py
- tests/test_schedulefree.py
Add Hessian in calculator using vmap or loop approach, based on @Nilsgoe PR. Hessian is not torchscript supported.
> add support for hessian in calculator

- README.md
- mace/cli/preprocess_data.py
- mace/cli/run_train.py
- mace/tools/scripts_utils.py
- mace/tools/train.py
- scripts/eval_mu_alpha.py
- setup.cfg
> Revert "Feat/mu alpha"

- docs/guide/ase.rst
> remove outdated docs line.

- mace/calculators/mace.py
> Fix compile_mode in MACECalculator

- mace/tools/train.py
Resolves https://github.com/ACEsuit/mace/issues/646
Increased loss output to 8 digits and MAEs to 2 digits.
> Increasing loss output digits

- mace/cli/active_learning_md.py
- mace/cli/create_lammps_model.py
- mace/cli/eval_configs.py
- mace/cli/fine_tuning_select.py
- mace/cli/plot_train.py
- mace/tools/arg_parser.py
This should resolve https://github.com/ACEsuit/mace/issues/644
> List default arguments with --help

- mace/tools/arg_parser_tools.py
> Enable swa if start_swa was given

- setup.cfg
> `setup.cfg` allow `nump>=2`

- mace/cli/select_head.py
closes #940 
Do we need to check other cli interfaces for this issue?
> Pass map_location=device to select_head.py torch.load

- README.md
- mace/calculators/foundations_models.py
- mace/tools/multihead_tools.py
https://github.com/ACEsuit/mace-mp -> https://github.com/ACEsuit/mace-foundations
> Update README and `foundations_models.py` to new repo URL

- mace/calculators/foundations_models.py
Add support for auto-downloading omat-small-0 model
> Add omat-small-0 to shortcuts for foundation models
