mace/data/utils.py

Nearly trivial change that uses `atoms.info["config_weight"]` if present to override weight from `atoms.info["config_type"]`
I'd really like per config energy, force, and stress weights, but that's deeper in the torch code.

Enable per-config weight in mace data reading

---

mace/calculators/mace.py
mace/modules/models.py
mace/modules/utils.py
tests/test_calculator.py
tests/test_run_train.py

Add stress (and free_energy) to MACECalculator.
PR comparison base should really be after merge of per_config_EFSV_weight, but that doesn't work because those are both in bernstei repo.  Will adjust base repository if needed once #22 is merged.
closes #3
closes #31

ASE Calculator stress

---

mace/calculators/mace.py

Changed the stress return format to align with the standard ase format by using only the 6 independent terms (Voigt notation).

Change stress to Voigt notation

---

mace/modules/irreps_tools.py

Reordering the interactions in the same order as the outputs simplifies the structure of the weights.
This help to convert the weights from `torch` to `jax`.

sort instructions in tp_out_irreps_with_instructions

---

mace/modules/models.py

write back the interaction energy from the scale shift mace model

openmm-interop compatibility changes

---

README.md

Updated the installation instructions in the readme for new users, so they use the correct conda channel for pytorch as well as CUDA 11.6. Added the installation of main dependencies with conda as well there.
see  https://pytorch.org/blog/pytorch-enterprise-support-update/ for information about deprecation

update installation instructions in readme

---

README.md
mace/data/utils.py
mace/modules/blocks.py
mace/tools/__init__.py
mace/tools/arg_parser.py
mace/tools/scatter.py
mace/tools/scripts_utils.py
mace/tools/torch_geometric/dataloader.py
mace/tools/torch_geometric/dataset.py
mace/tools/torch_tools.py
mace/tools/train.py
scripts/run_train.py
setup.cfg
tests/test_data.py

This pull requests implements the option to track experiments using Weights and Biases as an optional dependency. 
Other small enhancements are specifying hidden irreps via `num_channels` and` max_L` and logging of average number of neighbours precisely.

Weights and Biases support

---

scripts/eval_configs.py

Small fixes and clean-up of the evaluation code.

Debug and clean up evaluation code

---

mace/tools/torch_tools.py

Stress can either be supplied in Voigt notation (6,) or as a full 3x3 matrix. If the stress property has any other shape an error should be raised. 
If a (n,) vector is supplied, the first six elements are taken to be stress matrix in Voigt notation. Hence if a flattened 3x3 matrix (ie of shape (9,)) is supplied, one would obtain insensible stresses.

Require stress in shape (3,3) or (6,)

---

mace/calculators/mace.py
scripts/active_learning_md.py

This PR provides:
1. A mace calculator for using mace committees as a metric for model error
- A list of mace models can be supplied to a given calculator. The calculator returns the variance between the predictions in energy in forces as a metric for the predicted model error. 
- This method has been tested for committees, consisting of mace models trained on different random train/validation splits. 
2. A script for active learning using MD
- As an example use case of the calculator a quick AL script is included. This simply runs MD until the predicted error reaches a set threshold.

Committee error

---

mace/data/hdf5_dataset.py

If a `h5py.File` object is an attribute of the Dataset, pickle will complain that the file is not pickleable. 
This change resolves that by making file a property that is constructed and cached when it is first accessed. This allows the `h5py.File` to be excluded when pickling.

Slight modification to HDF5Dataset

---

mace/tools/arg_parser.py
mace/tools/scripts_utils.py
mace/tools/slurm_distributed.py
mace/tools/train.py
mace/tools/utils.py
scripts/distributed_example.sbatch
scripts/run_train.py
setup.cfg

Currently suitable for Slurm clusters. Compatible with HDF5. I didn't encounter any issues with HDF5 parallel data loading using 8 CPU workers per GPU, but this isn't thoroughly tested. Training is parallelized, but validation is done on a single GPU (to be amended in a future pull request). Example script - 2 nodes/20 GPUs, loading from HDF5 - provided at scripts/distributed_example.sbatch.

Multi-node, multi-GPU data parallel training.

---

README.md

Add readme section 'Pretrained Universal MACE Checkpoints'

---

README.md
docs/examples/training_examples.rst
docs/guide/evaluation.rst
docs/guide/lammps.rst
docs/guide/training.rst

Updated in various docs file.  Note that there's a reference to `preprocess_data.py`, whose path I updated, although it doesn't actually seem to exist anymore.

Update all docs references to contents of scripts/ to mace/cli/

---

mace/calculators/foundations_models.py
mace/calculators/mace.py

Currently calling `mace_mp` with no args issues warning
> `model_path` argument deprecated, use `model_paths`
Also, adding to @chiang-yuan to Matbench Discovery list of authors in `mace_mp` doc string.

Fix deprecation warning from default `mace_mp()` behavior

---

README.md
mace/calculators/foundations_models.py

Was trying to download from 
```py
urllib.request.urlretrieve(model, cached_model_path)
```
which should have been
```py
urllib.request.urlretrieve(checkpoint_url, cached_model_path)
```
since `model` can be `None`. Thanks @utf for reporting.

Fix `mace_mp` download

---

mace/cli/run_train.py
mace/tools/utils.py

Pass `max_L` argument to `load_foundations`, and use it to control j (# of contractions) loop

load_foundations support for max_L other than 2

---

mace/tools/train.py

Refactor logging of validation error in tools/train.py so that it can be called before any training has taken place

print validation error before any training

---

mace/calculators/foundations_models.py

Based on this answer https://stackoverflow.com/a/35160609 and my own testing, appending `?confirm=yTib` to the download URL avoids the Google Drive virus scan page that the model checkpoint links are automatically redirected to.
I confirmed locally that this resolves the pickle error reported by @Andrew-S-Rosen and also seen in [`matcalc`](https://github.com/materialsvirtuallab/matcalc/actions/runs/7486930755/job/20378280067):
```py
>       magic_number = pickle_module.load(f, **pickle_load_args)
E       _pickle.UnpicklingError: invalid load key, '<'.
/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/torch/serialization.py:1246: UnpicklingError
```

Add link to github models

---

mace/tools/slurm_distributed.py

If the slurm job is started with --ntasks_per_node and --nnodes, rather than --ntasks, the env vars currently expected aren' present. Fix that parsing.
Note that I think it'd be good to make the interface to this more general. Maybe all that's needed it to remove "slurm" from the `slurm_distributed.py` filename and check the possible env vars of different queuing systems (maybe not even actually implement any yet, but at least structure it that way).

Handle a wider range of possible slurm env vars

---

README.md

As title, we need to warn users the energy are raw vasp output without post-hoc corrections. Otherwise people are going to use it to create their benchmarks and make wrong claims

add note on mp corrections on energies

---

mace/tools/torch_tools.py
tests/test_compile.py

This PR follows up the earlier torch.compile support #300 and aims to make the input test a bit more realistic with 64 carbon atoms.   Added additional test cases that use the [pytest-benchmark](https://pypi.org/project/pytest-benchmark/) plugin to collect timings for different options.
One subtlety/controversial change is that the correctness test (`test_mace`) now uses `torch.testing.assert_allclose` as this uses more permissive comparison tolerances than using `assert torch.allclose` directly.
Measuring the inference time on an A10G:
|  | Time (ms) | Speedup vs eager fp64 |
|--------|--------|--------|
| Eager fp64 | 65.1 | 1 |
| Eager fp32 | 23.4 | 2.8 |
| compile default fp32 | 11.17 | 5.8 |
| reduce-overhead fp32 | 9.75 | 6.7 | 
| compile default mixed precision | 8.84 | 7.4 | 
| …

Update compile test case to use larger test system

---

mace/calculators/foundations_models.py

This PR adds the `damping` parameter to the foundation model calculator, which defaults to "bj" for backwards compatibility (and because it makes the most sense). This is also done for added clarity, as it's not mentioned anywhere in the docstring whether a damping function is used. In fact, at a quick glance, the user might be misled to thinking no damping is used since "D3" is printed to screen even though it is actually D3(BJ).

Add an option to set the D3 damping function, which defaults to D3(BJ)

---

mace/calculators/foundations_models.py

if you copy the URLs from the source code and pass it explicitly as `mace_mp(model="http://tinyurl.com/5yyxdm76")`, you get
```py
ValueError: Couldn't find MACE model files: http://tinyurl.com/5yyxdm76
```
using http**s** which is safer anyway fixes this

Use HTTPS for MACE MP checkpoint URLs

---

mace/data/utils.py

Make sure that configurations of len 1 that are not `IsolatedAtom` are not ignored
closes #381

Fix logic that deals with IsolatedAtom and 1-atom configuration

---

mace/calculators/mace.py

Initial form of this PR allows `MACECalculator` to override `Atoms.info["theory"]` when deciding which head to use for prediction. This is the minimal change I need to be able to use such models cleanly, but I'm not sure it's sufficient.
Other related things I've noticed
- if you don't specify a theory (i.e. nothing in info `"theory"` field), it prints an error about `'Default'` not matching. I think it's from https://github.com/ACEsuit/mace/blob/5a66ca442391a73e81bf4cadcfec22d6d31c3c96/mace/data/atomic_data.py#L131
- I'm not sure defaulting to any particular theory (first, as it does now, or any other arbitrary choice, like last) is a good idea to begin with. However, this choice might be related to details of the multi-head **fitting** (e.g. if we're using multi-head to stabilize …

Allow MACECalculator to pick theory used for multihead models

---

mace/tools/train.py

Make sure check for patience does not try to use swa.start if it is None, in two tests: switching to swa, and terminating iterations altogether.

Fix check for patience that fails if swa start was not specified

---

mace/cli/run_train.py
mace/data/utils.py

Actually store multihead fine-tuning pbe mp forces in `Atoms.arrays`, rather than incorrect current storage in `Atoms.info`
Also, store configs selected when multihead fine-tuning in local, tag dependent filename, rather than fixed filename in `~/.cache/mace`

fix incorrect conversion of forces from calculator to atoms.arrays for finetuning pbe mp replay head

---

mace/tools/train.py

Check for `swa is None` rather than `swa.start is None` when doing patience checks

Better fix for PR #405, fix patience check when swa is not active

---

mace/calculators/foundations_models.py
mace/cli/preprocess_data.py
mace/cli/run_train.py

preprocess_data.py cannot be used with a tutorial provided code in the README file, because of the wrong parsing function

removed wront argument parsing in preprocess_data

---

mace/calculators/mace.py
tests/test_calculator.py

Fixed a bug when using the MACE calculator to calculate node interaction energies.
Previously, the isolated atom energy was being subtracted twice. Note, I had to modify the `fitting_configs` fixture to add E0s to the configs there, otherwise this bug was not being caught even with the old implementation.
Also, I added an additional helper function to the calculator to batchify the atoms since the exact same code was used in two places within the calculator.
Also, changed the name of the function `_prepare_batch`  to `_clone_batch` to better reflect what it is doing.
This should also resolve the following discussion:
https://github.com/ACEsuit/mace/discussions/417

fix atom e0s being subtracted twice in mace calculator

---

mace/cli/fine_tuning_select.py

Don't apply `np.random.choice` to `list(Atoms)` since it thinks it's multiidimensional
closes #447

fix np.random.choice issue when subselecting from pre-trained configs for multihead fine tune

---

mace/tools/train.py

When printing validation loss during training, pass loss for head, not partial sum over heads calculated so far
closes #444

validation loss printed during training is not actually for the specific head

---

mace/cli/run_train.py
mace/tools/arg_parser.py
mace/tools/scripts_utils.py
mace/tools/train.py
setup.cfg
tests/test_schedulefree.py

This implements the schedule free optimizer (https://github.com/facebookresearch/schedule_free) and adds it as an optional dependency.
Initial tests suggest a slight improvement over adamW using 3BPA as a test system.
This PR also fixes a small bug for writing `config.yaml` files when training a single layer model.

Support for schedulefree optimizer

---

.github/workflows/pre-commit.yaml
.github/workflows/release.yaml
.github/workflows/unittest.yaml
README.md

As discussed with @alinelena and @ilyes319, adds release workflow to automate releasing on tagged commits.
Tested on my fork: https://github.com/ElliottKasoar/mace/releases
Once set up, each release would then be preserved via zenodo (see [GitHub ](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content)/ [Zenodo](https://zenodo.org/account/settings/github/) instructions).
An admin of the repository can reserve a DOI, so we can update the placeholders in the README before the next release, which should then immediately link correctly.
It would also be relatively straightforward to extend this workflow e.g. to use different build systems, or release to PyPI etc.
(Note: this also bumps versions in other GitHub Actions, but this can be …

Add DOI badge and automated release

---

mace/data/neighborhood.py
mace/data/utils.py
mace/modules/utils.py

- Change compute of volumes to unsigned volumes as ASE convention
- Fix PBC extension for slabs, in case of non diag cells.

correct pbc extension

---

README.md

Make the installation steps simpler in the readme. For PyTorch just link to the official and up to date documentation.

Simplify installation steps

---

mace/calculators/foundations_models.py

to only download and return path to checkpoint. for use with [`openmmml.MacePotential`](https://github.com/openmm/openmm-ml/blob/c68fcbd7513567cff6fa50cc27b4120d6b966f07/openmmml/models/macepotential.py#L45-L88) which requires a `modelPath` rather than an ASE calculator. `mace_mp` previously didn't expose the auto-downloaded checkpoint path except by extracting it from the function's `print` output

Split `download_mace_mp_checkpoint` out of `mace_mp`

---

mace/calculators/foundations_models.py
mace/calculators/mace.py
mace/cli/active_learning_md.py
mace/tools/scripts_utils.py
tests/test_calculator.py
tests/test_run_train.py

The current `MACECalculator` requires you to load from a particular structure of checkpoint file. If we use a different training framework our checkpoints are not compatible and so it would be nice to be able to just pass in models.
~~Still needs tests.~~

Allow creation of MACECalculator without needing to write a checkpoint to disk.

---

.pre-commit-config.yaml
README.md
mace/calculators/mace.py

Remove the `|` in the type hint syntax that is incompatible with python 3.9.  I don't know if there are other places where this syntax is being used - if there is auto testing (esp. in a github CI), perhaps it could automatically be run with python 3.9 in addition to whatever version is being used now?  Maybe run on 3.9, for backward compatibility, and some new-ish version (3.12 now?) for cutting edge support?
closes #617

Change type hint syntax in MACECalculator to work with python39

---

mace/cli/eval_configs.py

When constructing the `DataLoader`, it appears that the keyword passing the `heads` of the model to the function was missing, so I added it in the PR.
I also added an additional argument to the CL function, that should make it much more convenient to evaluate all structures on a single head. Specifying it for every structure in the extxyz file is a bit clunky, if that flexibility is not required.
Let me know, what you think or if I got something wrong and it was indeed working all along (it didn't for me).

Fix multihead prediction for eval_configs.py

---

mace/tools/compile.py
setup.cfg
tests/test_compile.py

torch compile is under active development so the mace compile support needed a few updates to keep up with recent torch releases.  This PR:
* adds pytest-benchmark to the development install of mace
* removes usage of an API that doesn't exist in pytorch 2.3 and up
* updates the test cases to use `ScaleShiftMACE` as I understand this is the most widely used model implementation
* removed the `fullgraph=True` option which was triggering a compiler assertion for using `requires_grad_` on the model input tensors. I think this assertion is ok to ignore since the test case that checks for graph breaks is still passing.
* skipping the mixed-precision benchmark as this fails with an assertion on mismatched datatypes in the scatter operation.
I'd prefer to leave the mixed-precision test case in …

Updating compiler support and test cases

---

mace/tools/scripts_utils.py
tests/test_run_train.py

To resolve issue https://github.com/ACEsuit/mace/issues/651

Turn json keys representing elements into ints

---

mace/tools/checkpoint.py

This should fix a the file name given to the checkpoint after the very first swa epoch.
Currently, swa is started in `train.py` when `epoch == swa_start`, but the checkpoint file name only adds "swa" to the file name when `epoch > swa_start`.
This leads to a problem, when the first swa epoch has the lowest loss of all validated swa epochs. The checkpoint is saved under the wrong name, never overwritten and, at the end of the training, this checkpoint is saved as the best non-swa checkpoint (if the loss is lower then for any stage-one checkpoint), whereas the swa checkpoint is not found and an error is thrown.

Fix file name of swa checkpoints

---

mace/tools/finetuning_utils.py

Transferring original weights in foundation model correctly because of the new class name and an extra `density_fn` layer in interaction blocks.

Fixing multihead finetuning with density normalization

---

mace/data/utils.py

See [issue](https://github.com/ACEsuit/mace/issues/680).
I am not sure what the desired behaviour is here. Do we want the user to be able to specify 'head_key'='head_name' in the input xyz files? This fix would override that.
Using the main branch, adding `head=MP2` to a configuration's info dict does indeed add a row 'Default_MP2' to the output table.
```
2024-11-25 11:54:00.502 INFO: Error-table on TEST:
+----------------+---------------------+------------------+-------------------+
|  config_type   | RMSE E / meV / atom | RMSE F / meV / A | relative F RMSE % |
+----------------+---------------------+------------------+-------------------+
| NaCl_8_Default |          425.1      |         59.0     |          7.43     |
|   NaCl_8_MP2   |          337.9      |         91.3     | …
```

Evaluate test sets separately for different heads

---

mace/tools/arg_parser.py
tests/test_preprocess.py

Enables configuration files to be passed to pre-processing through `build_preprocess_arg_parser`, in the same way as [the default parser](https://github.com/ACEsuit/mace/blob/main/mace/tools/arg_parser.py#L12).

Add pre-processing config file option

---

.gitignore
mace/tools/torch_tools.py
tests/test_benchmark.py

This PR adds dual-use unittests and benchmarks to begin addressing #645.  It would be helpful to have feedback on how representative these benchmarks are compared to production MD runs with either LAMMPS or OpenMM.
The benchmarks run as normal unittests and I found that adding the option to run the benchmark on the compiled variant significantly increased the time it takes to collect the performance metrics.  
Running the benchmarks:
```
pytest tests/test_benchmark.py --benchmark-save=<some name>
```
to include metrics with torch.compile:
```
MACE_FULL_BENCH =1 pytest tests/test_benchmark.py --benchmark-save=<some name>
```
After saving some metrics, invoking the test file as a script will output the collected metrics as a csv:
```
python tests/test_benchmark.py
```
The benchmark …

Add mace_mp medium performance benchmark

---

mace/cli/select_head.py

Embed head name in default output filename, and fix reference to non-existent target_device argument. Also add argument to list available heads.
closes #771

Fix default outpout_file in select_head, and add argument to list heads

---

mace/cli/preprocess_data.py

If the input `.xyz` for preprocessing has more `IsolatedAtom`s than elements in the training configs, training with the generated statistics.json fails.
```
[rank4]: Traceback (most recent call last):
[rank4]:   File "/lustre/fswork/projects/rech/gax/ums98bp/maces/main/scripts/run_train.py", line 6, in <module>
[rank4]:     main()
[rank4]:   File "/lustre/fswork/projects/rech/gax/ums98bp/maces/main/mace/cli/run_train.py", line 66, in main
[rank4]:     run(args)
[rank4]:   File "/lustre/fswork/projects/rech/gax/ums98bp/maces/main/mace/cli/run_train.py", line 572, in run
[rank4]:     model, output_args = configure_model(args, train_loader, atomic_energies, model_foundation, heads, z_table)
[rank4]:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```

Remove entries from atomic_energies_dict if not in z_table

---

docs/guide/cuda_acceleration.rst

`pip install cuequivariance==0.1.0 cuequivariance-torch cuequivariance-ops-torch-cu12`
installs cuequivariance==0.1.0,  cuequivariance-torch==0.2.0, and  cuequivariance-ops-torch-cu12==0.2.0
It must be `pip install cuequivariance==0.1.0 cuequivariance-torch==0.1.0 cuequivariance-ops-torch-cu12==0.1.0` until `cuequivariance=0.2.0` is supported in MACE.

pinned cuequivariance-torch & cuequivariance-ops-torch-cu12 to 0.1.0

---

mace/tools/scripts_utils.py

Fixes second stage weight logging mistake, that printed first stage stress weight instead of second stage. Raised in https://github.com/ACEsuit/mace/discussions/895

fix swa stress logging

---

mace/cli/run_train.py
mace/tools/default_keys.py
tests/test_run_train_allkeys.py

Fixes the keyspec object being modified in place during multihead finetuning.
Also adds tests that check for this behaviour.
This fixes issue 933.

fix keyspec being modified inplace

---

mace/calculators/mace.py

When defaulting to a head named default from a multihead finetuned model, search, don't just assume it's the first in available list.
closes #930

MACECalculator search for head named 'default' when no head is specified explicitly

---

mace/tools/model_script_utils.py

Output actual loss to be used, rather than hard-wired string 'universal' when reporting on model to be used when fine-tuning is active
closes #972

correct output of loss to log file when fine-tuning

---

mace/cli/eval_configs.py
mace/modules/extensions.py
mace/modules/models.py
mace/tools/arg_parser.py
mace/tools/model_script_utils.py
mace/tools/scripts_utils.py
setup.cfg
tests/test_maceles.py

This PR re-implements the MACELES model , updating it for compatibility with the current develop branch. Original PR #934 by @BingqingCheng.
The new implementation has been checked against the old one. It initializes identically, and forward passes on the same data with freshly initialized models produce the same results.
A key correction is the inclusion of the `les_readouts` parameters in the optimizer. These parameters were previously not part of the parameter groups and were therefore not being trained. This PR corrects that. The new implementation also supports initializing a MACELES model from a foundation model checkpoint.
- Given that `les_readouts` were not trained, was it the original intention for the latent charges to be derived from a fixed random projection of the node …

Reimplementation of MACELES

---

mace/cli/run_train.py
mace/data/utils.py
mace/tools/arg_parser.py

Correct numerator in ratio of real to pretrain configs when checking ratio to see if duplicating real configs is needed.
Also (incidentally) remove unneeded debugging prints.
closes #1108

Fix test of real to pretrain data ratio for repeating configs

---

mace/calculators/mace.py
mace/cli/run_train.py
mace/cli/visualise_train.py
mace/data/atomic_data.py
mace/data/utils.py
mace/modules/__init__.py
mace/modules/blocks.py
mace/modules/loss.py
mace/modules/models.py
mace/modules/utils.py
mace/tools/arg_parser.py
mace/tools/default_keys.py
mace/tools/model_script_utils.py
mace/tools/scripts_utils.py
mace/tools/slurm_distributed.py
mace/tools/tables_utils.py
mace/tools/torch_tools.py
mace/tools/train.py
tests/test_calculator.py
tests/test_models.py

I updated the old `MACE/mu_alpha` branch to the current main branch. It passes all tests of the current main branch.
In addition to the `AtomicDipolesMACE` and `DipoleMACE` models, it now also includes the `AtomicDielectricMACE` and `DipolePolarizabilityMACE` models. This allows users to train and calculate polarizabilities and dipoles. I am aware that there is some redundancy in having both sets of models in the code, but for backward compatibility, it might be useful to keep the old models available. Also one can then still have a L=1 model for the dipoles and doesn't need to train a L=2 model.
I tested the model with different SPICE subsets, and the training and prediction works fine.
I can also add a brief script on how to obtain the polarizabilities using ASE via …

Updated MACE mu alpha

---

mace/data/atomic_data.py
mace/tools/utils.py

There was a small bug in the training of the polarizability, where the dimensions of the polarizability_weight had not been properly added with regard to some other updates made in the version update. Unfortunately, this bug prevented the model from training at all.
@ilyes319 I would highly recommend merging this directly into the main branch; otherwise, the training on polarizabilities won't be supported at all

Hotfix: Solving weight shape error for polarizability_weights

---

mace/tools/arg_parser.py

Fixes default argparser values for `--compute-polarizability` and `--compute_atomic_dipole`. Previous values raised ValueErrors when trying to train while using weights and biases.

fix parser default values

---

docs/guide/hessian.rst
docs/guide/polarizability.rst

I added some documentation on how one could train an AtomicDielectricMACE and how to get the polarizability with ASE. I also added the citation for the Hessian paper to the respective page in the documentation.

Docs: add polarizability example and Hessian citation

---

mace/calculators/mace.py
mace/modules/models.py

Now, `AtomicDielectricMACE` models from legacy versions of the code are also supported. For example, models from [https://github.com/venkatkapil24/MACE-OFF-mu-models](https://github.com/venkatkapil24/MACE-OFF-mu-models). 
Credits to @cecicxy, who reported the problem in this [issue](https://github.com/venkatkapil24/MACE-OFF-mu-models/issues/2) .

Fix: Old AtomicDielectricMACE models trained only on Dipoles were not properly supported.
